export const allowedRpcMethods = [
  "node_info",
  "connect_peer",
  "disconnect_peer",
  "list_peers",
  "open_channel",
  "open_channel_with_external_funding",
  "accept_channel",
  "list_channels",
  "update_channel",
  "shutdown_channel",
  "submit_signed_funding_tx",
  "new_invoice",
  "parse_invoice",
  "get_invoice",
  "cancel_invoice",
  "send_payment",
  "get_payment",
  "build_router",
  "send_payment_with_router",
  "list_payments",
  "graph_nodes",
  "graph_channels",
  "sign_external_funding_tx",
] as const;

export type AllowedRpcMethod = (typeof allowedRpcMethods)[number];
